services:
  - type: web
    name: kinobot
    runtime: python
    repo: https://github.com/kinouzb/Kinobotlari
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    pythonVersion: 3.10.12
